build_image: shippableimages/ubuntu1404_python
language: python
compiler: gcc

before_install:
  - lsb_release -a
  - sudo apt-get install libboost-test-dev libboost-system-dev libboost-filesystem-dev libboost-thread-dev libboost-context-dev libboost-coroutine-dev
  - sudo apt-get install libapr1
  - sudo apt-get install cmake


before_script:
   - mkdir build
   - cd build
   - cmake ..

script: make
