build_image: shippableimages/ubuntu1404_python
language: python
compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-dev libboost-system-dev libboost-thread-dev libboost-filesystem-dev libboost-test-dev libboost-coroutine-dev libboost-context-dev libboost-program-options-dev libboost-regex-dev
  - sudo apt-get install -y libapr1-dev libaprutil1-dev libaprutil1-dbd-sqlite3
  - sudo apt-get install -y liblog4cxx10-dev liblog4cxx10
  - sudo apt-get install -y libjemalloc-dev
  - sudo apt-get install -y libsqlite3-dev
  - sudo apt-get install -y libmicrohttpd-dev
  - sudo apt-get install -y cmake


before_script:
   - mkdir build
   - cd build
   - cmake ..

script: 
   - make -j4
   - make test
   - functests/storage_test /tmp
