sudo: required

dist: trusty

group: edge

compiler: gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
      - GENERIC_BUILD=false
    - os: linux
      dist: trusty
      sudo: required
      env:
      - GENERIC_BUILD=true
    - os: osx
      osx_image: xcode9.2
      env:
      - GENERIC_BUILD=false

env:
  global:
  - secure: DHaTv1euwlpVgePMbw0LEBihzru8VP5RmY7/TUdEpS1dBlJx6nyT6lgmyRcdb19RmTBUXZl1hm7Zu8TfqJJgfty4o9EnpLfTHbY7JwglSqbOo7b/FNAa1Qi0RhVDwc/WvFJDYBUvOtPtVQbPtVtECXm8PZcRqfOuEjkbHmmnIk8=

addons:
  artifacts:
    provider: s3
    s3_region: us-west-2
    access_key_id: "$ARTIFACTS_KEY"
    secret_access_key: "$ARTIFACTS_SECRET"
    bucket: "$ARTIFACTS_BUCKET"
    acl: public_read
    paths:
    - "$HOME/akumuli.log"

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew update;              fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then sh prerequisites-osx.sh;  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update;      fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sh prerequisites.sh; fi

before_script:
- mkdir build
- cd build
- if [[ $GENERIC_BUILD == true ]]; then
  cmake .. -DCMAKE_BUILD_TYPE=ReleaseGen;
  else
  cmake .. -DCMAKE_BUILD_TYPE=Release;
  fi

script:
- make -j4
- ctest -VV
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh runci_osx.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh runci_linux.sh; fi
- cpack
- cp akumuli_*_amd64.deb ./docker
# Build docker container
- export REPO=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "akumuli/akumuli"; else echo "akumuli/test"; fi`
- export TAG=`if [[ $GENERIC_BUILD == "false" ]]; then echo "skylake"; else echo "generic"; fi`
- docker build -t $REPO:$TAG ./docker
deploy:
  provider: packagecloud
  repository: Akumuli
  username: Lazin
  dist: ubuntu/trusty
  package_glob: "./*.deb"
  token:
    secure: TNIqxlIMy4PUJIn65Yl7dyr1A+TVCMSCOUZOd/XlqlmjntFbxdBKY2M+bX5Cc+uOvNNxFU0m0/RpxYibeN8Juo3BTV0B8YJ4Hjr60F+Sag0UFvvDmxd4vzK+rm+XbYyyx0ukO2ETUxEqxaJaEi0CJPEvEiIeXyJAzIytoVNukkM=
  on:
    os: linux
    branch: master
    condition: $GENERIC_BUILD = "false"
  skip_cleanup: true
after_success:
- if [[ $TRAVIS_PULL_REQUEST == "false" && "$TRAVIS_OS_NAME" == "linux" ]]; then
  docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
  docker push $REPO:$TAG;
  fi 
after_failure: 
