build_environment: shippableimages/ubuntu1404_python
language: python
compiler: gcc

before_install:
  - lsb_release -a
  - sudo apt-get install libboost1.54-dev
  - sudo apt-get install libapr1
  - sudo apt-get install cmake

before_script:
   - mkdir build
   - cd build
   - cmake ..

script: make
