build_image: shippableimages/ubuntu1404_python
language: python
compiler: gcc

before_install:
  - lsb_release -a
  - sudo apt-get install libboost-dev
  - sudo apt-get install libapr1
  - sudo apt-get install -y cmake


before_script:
   - mkdir build
   - cd build
   - cmake ..

script: make
